### ISSUE TITLE
推荐发送邮箱验证码进行注册

### ISSUE THREAD

**Issue by fengwenyi** [FdogMain/FdogInstantMessaging#3]
1、发送邮箱是免费的，建议使用邮箱验证码，进行注册。

2、我是做Java后端开发，可以为你提供技术支持，如果需要的话，你可以专注前端开发，我不擅长。

**Comment by HuaGouFdog** [comment]
1. 邮箱的话，之前有尝试过，但是还是感觉在注册方面不如手机验证码好，我目前又购买了一些短信用于测试。邮箱验证码倒是可以用于找回密码啊，修改密码之类的业务，可以分担一部分短信压力。
2. 我之前利用在学校学的java写的后端，前端用的jsp，写的一塌糊涂，前后端没有分离，有人建议我使用go，然后我目前在实习，这边也是有使用go的环境，所以我也顺便学习了一下，这两天我使用go重新了后端，前后端分离，感觉比java好一点，个人感觉哈，所以想着用go把java替代。我也不知道对不对！～

**Comment by fengwenyi** [comment]
注册体验好不好用，并不影响，你可以把经历放到其他方面。
首先，用短信验证码，如果遇到恶意请求，你怕是遭不住的。
另外，你这是一款即时聊天，那么他的主要功能在于功能，不是说登录注册就是主要功能了，也不是简单的聊天，要在于及时性。只有你的聊天功能能达到微信，不说QQ吧，就很好了，不在于用什么注册。
及时聊天，再大的问题，应该是聊天的即时性，不要管页面啊，用的多了  能不能承受得了，用什么语言不重要的。
